name: watch_hub
description: "A Watch Shopping Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  image_picker: ^1.1.1
 
  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # Navigation / Routing
  go_router: ^14.2.0

  # For API / JSON data
  http: ^1.2.2

  # Carousel Slider for Home Banners
  carousel_slider: ^5.0.0

  # Shimmer Loading Animation âœ¨
  shimmer: ^3.0.0

  firebase_storage: ^13.0.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/new.jpg"
  adaptive_icon_background: "#000000"   # background color (can change)
  adaptive_icon_foreground: "assets/images/new.jpg"
